<?php

declare(strict_types=1);

return [
    [
        'id' => 1,
        'nombre' => 'Oxapampa',
        'region' => 'Pasco',
        'descripcion' => 'Capital cafetalera y puerta de entrada a la Reserva de Biosfera Oxapampa-Ashaninka-Yanesha.',
        'tagline' => 'Naturaleza, cultura y café en un solo destino.',
        'latitud' => -10.5756,
        'longitud' => -75.4018,
        'imagen' => 'oxapampa.jpg',
        'imagen_portada' => 'oxapampa.jpg',
        'imagen_destacada' => 'oxapampa.jpg',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['café de altura', 'naturaleza', 'cultura'],
        'estado' => 'activo',
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 2,
        'nombre' => 'Villa Rica',
        'region' => 'Pasco',
        'descripcion' => 'Tierra del café de altura, la Laguna El Oconal y miradores panorámicos.',
        'tagline' => 'Ruta cafetalera y experiencias de bienestar.',
        'latitud' => -10.7393,
        'longitud' => -75.2705,
        'imagen' => 'villa-rica.jpg',
        'imagen_portada' => 'villa-rica.jpg',
        'imagen_destacada' => 'villa-rica.jpg',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['café', 'bienestar', 'observación de aves'],
        'estado' => 'activo',
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 3,
        'nombre' => 'Pozuzo',
        'region' => 'Pasco',
        'descripcion' => 'Colonia austro-alemana rodeada de paisajes naturales y tradiciones vivas.',
        'tagline' => 'Historia europea en medio de la selva peruana.',
        'latitud' => -10.0683,
        'longitud' => -75.5496,
        'imagen' => 'pozuzo.jpg',
        'imagen_portada' => 'pozuzo.jpg',
        'imagen_destacada' => 'pozuzo.jpg',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['historia', 'cultura', 'naturaleza'],
        'estado' => 'activo',
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 4,
        'nombre' => 'Perené',
        'region' => 'Chanchamayo',
        'descripcion' => 'Cataratas, mariposarios y comunidades nativas en plena Amazonía alta.',
        'tagline' => 'Aventura y cultura amazónica.',
        'latitud' => -10.9639,
        'longitud' => -75.2342,
        'imagen' => 'perene.jpg',
        'imagen_portada' => 'perene.jpg',
        'imagen_destacada' => 'perene.jpg',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['cascadas', 'comunidades nativas', 'aventura'],
        'estado' => 'activo',
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 5,
        'nombre' => 'Yanachaga',
        'region' => 'Pasco',
        'descripcion' => 'Reserva nacional que resguarda bosques de neblina, fauna endémica y experiencias de conservación.',
        'tagline' => 'Santuario de biodiversidad altoandina.',
        'latitud' => -10.4586,
        'longitud' => -75.2686,
        'imagen' => 'yanachaga.jpg',
        'imagen_portada' => 'yanachaga.jpg',
        'imagen_destacada' => 'yanachaga.jpg',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['biodiversidad', 'senderismo', 'conservación'],
        'estado' => 'activo',
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
];
