<?php

declare(strict_types=1);

return [
    [
        'id' => 1,
        'nombre' => 'Amazonas',
        'region' => 'Amazonas',
        'descripcion' => 'Explora Kuélap, la catarata Gocta y pueblos que resguardan el legado chachapoya.',
        'tagline' => 'Aventura andino-amazónica en el norte peruano.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['cataratas', 'arqueología', 'selva alta'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 2,
        'nombre' => 'Áncash',
        'region' => 'Áncash',
        'descripcion' => 'Cordillera Blanca, lagunas turquesas y pueblos artesanales para los amantes del trekking.',
        'tagline' => 'Capital del andinismo peruano.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['montaña', 'trekking', 'lagunas'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 3,
        'nombre' => 'Apurímac',
        'region' => 'Apurímac',
        'descripcion' => 'Cañones profundos, puentes colgantes y comunidades vivas a orillas del río Apurímac.',
        'tagline' => 'Paisajes majestuosos y cultura ancestral.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['aventura', 'cultura viva', 'montaña'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 4,
        'nombre' => 'Arequipa',
        'region' => 'Arequipa',
        'descripcion' => 'La Ciudad Blanca ofrece volcanes, monasterios coloniales y gastronomía reconocida a nivel mundial.',
        'tagline' => 'Volcanes, historia y sabor.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['volcanes', 'gastronomía', 'historia'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 5,
        'nombre' => 'Ayacucho',
        'region' => 'Ayacucho',
        'descripcion' => 'Semana Santa, artesanías y pueblos que conservan tradiciones andinas inolvidables.',
        'tagline' => 'Capital del arte popular peruano.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['tradición', 'festividades', 'arqueología'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 6,
        'nombre' => 'Cajamarca',
        'region' => 'Cajamarca',
        'descripcion' => 'Campiñas verdes, aguas termales y patrimonio colonial en los Andes del norte.',
        'tagline' => 'Paisajes dorados y cultura viva.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['termales', 'historia', 'gastronomía'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 7,
        'nombre' => 'Cusco',
        'region' => 'Cusco',
        'descripcion' => 'Capital del Tahuantinsuyo con Machu Picchu, valles sagrados y experiencias andinas únicas.',
        'tagline' => 'Cuna del Imperio Inca.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['arqueología', 'gastronomía', 'aventura'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 8,
        'nombre' => 'Huancavelica',
        'region' => 'Huancavelica',
        'descripcion' => 'Cordilleras, termas y pueblos mineros que muestran la esencia de la sierra central.',
        'tagline' => 'Altiplano acogedor y termal.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['termales', 'tradición', 'montaña'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 9,
        'nombre' => 'Huánuco',
        'region' => 'Huánuco',
        'descripcion' => 'Bosques de neblina, café aromático y sitios arqueológicos como Kotosh.',
        'tagline' => 'Selva alta y legado preinca.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['café', 'naturaleza', 'historia'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 10,
        'nombre' => 'Ica',
        'region' => 'Ica',
        'descripcion' => 'Dunas infinitas, viñedos, oasis y líneas milenarias trazadas en el desierto.',
        'tagline' => 'Desierto y aventura costera.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['desierto', 'enoturismo', 'historia'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 11,
        'nombre' => 'Junín',
        'region' => 'Junín',
        'descripcion' => 'Selva central, lagunas altoandinas y gastronomía que mezcla la sierra y la Amazonía.',
        'tagline' => 'Puerta de la Selva Central.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['selva central', 'café', 'aventura'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 12,
        'nombre' => 'La Libertad',
        'region' => 'La Libertad',
        'descripcion' => 'Chan Chan, huacas milenarias y playas perfectas para el surf todo el año.',
        'tagline' => 'Arqueología y olas eternas.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['arqueología', 'surf', 'gastronomía'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 13,
        'nombre' => 'Lambayeque',
        'region' => 'Lambayeque',
        'descripcion' => 'Museos de clase mundial, bosques secos y tradiciones mochicas en cada ruta.',
        'tagline' => 'Tesoros del norte peruano.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1499696010181-2cb40af7859d?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1499696010181-2cb40af7859d?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1499696010181-2cb40af7859d?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['arqueología', 'gastronomía', 'bosque seco'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 14,
        'nombre' => 'Lima',
        'region' => 'Lima',
        'descripcion' => 'Capital gastronómica, litoral urbano y sitios arqueológicos prehispánicos.',
        'tagline' => 'Ciudad creativa junto al mar.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['gastronomía', 'cultura', 'litoral'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 15,
        'nombre' => 'Loreto',
        'region' => 'Loreto',
        'descripcion' => 'Navega por el Amazonas, descubre reservas naturales y comunidades indígenas.',
        'tagline' => 'Selva infinita y biodiversidad.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1529923188384-5e545b81d48d?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1529923188384-5e545b81d48d?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1529923188384-5e545b81d48d?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['amazonas', 'naturaleza', 'cultura indígena'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 16,
        'nombre' => 'Madre de Dios',
        'region' => 'Madre de Dios',
        'descripcion' => 'Collpas de guacamayos, lodges sostenibles y selva exuberante en Tambopata y Manu.',
        'tagline' => 'Capital de la biodiversidad peruana.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['biodiversidad', 'ecoturismo', 'amazonas'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 17,
        'nombre' => 'Moquegua',
        'region' => 'Moquegua',
        'descripcion' => 'Valles soleados, bodegas artesanales y paisajes volcánicos ideales para rutas gastronómicas.',
        'tagline' => 'Encanto sureño y sabores únicos.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['enoturismo', 'historia', 'gastronomía'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 18,
        'nombre' => 'Pasco',
        'region' => 'Pasco',
        'descripcion' => 'Bosques nublados, reservas protegidas y cultura austro-alemana en la selva central.',
        'tagline' => 'Naturaleza cafetera y aventura.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['café', 'bosque de neblina', 'aventura'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 19,
        'nombre' => 'Piura',
        'region' => 'Piura',
        'descripcion' => 'Playas cálidas, manglares y pueblos artesanos especialistas en sombreros y cerámica.',
        'tagline' => 'Sol eterno y sabor norteño.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['playas', 'gastronomía', 'artesanía'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 20,
        'nombre' => 'Puno',
        'region' => 'Puno',
        'descripcion' => 'Navega por el lago Titicaca, descubre islas flotantes y festividades llenas de color.',
        'tagline' => 'Corazón altiplánico del Perú.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['cultura viva', 'lago titicaca', 'festividades'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 21,
        'nombre' => 'San Martín',
        'region' => 'San Martín',
        'descripcion' => 'Tarapoto, Lamas y cataratas de fácil acceso en una selva cargada de aromas.',
        'tagline' => 'Escapadas tropicales todo el año.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['cataratas', 'gastronomía', 'naturaleza'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 22,
        'nombre' => 'Tacna',
        'region' => 'Tacna',
        'descripcion' => 'Historia republicana, baños termales y valles vitivinícolas al pie del desierto.',
        'tagline' => 'Patrimonio, termas y gastronomía.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['historia', 'enoturismo', 'termales'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 23,
        'nombre' => 'Tumbes',
        'region' => 'Tumbes',
        'descripcion' => 'Playas cálidas, manglares protegidos y avistamiento de fauna marina tropical.',
        'tagline' => 'Paraíso norteño de sol y mar.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['playas', 'manglares', 'biodiversidad'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
    [
        'id' => 24,
        'nombre' => 'Ucayali',
        'region' => 'Ucayali',
        'descripcion' => 'Rutas fluviales, comunidades shipibo-konibo y artesanía con identidad amazónica.',
        'tagline' => 'Amazonía creativa y espiritual.',
        'latitud' => null,
        'longitud' => null,
        'imagen' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'imagen_portada' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'imagen_destacada' => 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
        'galeria' => [],
        'video_destacado_url' => '',
        'tags' => ['amazonas', 'artesanía', 'naturaleza'],
        'estado' => 'activo',
        'visible_en_busqueda' => true,
        'visible_en_explorador' => true,
        'actualizado_en' => '2024-01-04T12:00:00-05:00',
    ],
];
